# Generated by Django 3.1.7 on 2021-02-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='month',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='year',
        ),
    ]
